#!/usr/bin/env ruby
#
# Create a new record in a Jekyll-datastore table
require 'fileutils'
require_relative 'libs/myfunctions.rb'

table = ARGV.first ? ARGV.first : "item"
time = Time.new
myUpDir = File.expand_path(File.dirname(__FILE__)+'/..')+'/'

print 'Title: '
title = gets.chomp
dest =  myUpDir+'_posts/'+time.strftime("%Y-%m-%d")+'-'+friendly_filename(title)+'.md'
source = myUpDir+'_models/'+table+'.md'
puts title
puts dest
puts source
FileUtils.cp(source,dest)

