#!/usr/bin/env ruby
#
# Create a new table in a Jekyll-datastore
require 'fileutils'
require 'open3'
require 'safe_yaml'
require_relative 'libs/myfunctions.rb'

table = ARGV.first ? ARGV.first : "item"
myUpDir = File.expand_path(File.dirname(__FILE__)+'/..')+'/'

print 'Name: '
name = gets.chomp
dest =  myUpDir+'_models/'+friendly_filename(name)+'.md'
source = myUpDir+'_models/'+table+'.md'

data = File.read(source)
yaml = YAML.safe_load(data)
data = data.sub("- items", "- items\n- "+name)
data = data.sub("pageFileName: "+yaml['tableConf']['pageFileName'],"pageFileName: "+friendly_filename(name)+".html")
File.open(dest, 'w') do |f|
  f.write(data)
end

# todo:: improve to make it work with Ubuntu and Windows
Open3.popen3("${VISUAL:-${EDITOR:-vi}} #{dest}")
